Add descriptions
fu050409/infini-coc pull request #1
Opened 2024-04-09 08:15 UTC by BegoniaHe

I've add some descriptions to the file handler(path=/src/handler) to describe the feature of instructions

2024-04-09 08:24 UTC, fu050409 requested changes

2024-04-09 08:24 UTC, fu050409 commented on src/handlers.py
> +    sub_cmd="\n[掷骰表达式]    掷骰表达式\ncheck   检定人物当前生命状态"
请注意检查类型，sub_cmd是dict类型的参数，传入字符串会导致世界树和夜骰帮助核心出现未知异常。

2024-04-09 08:24 UTC, fu050409 commented on src/handlers.py
> +    description="基础属性或技能检定\n示例：\n.ra 命运    快速检定`命运`属性\n.ra 毁灭人类 99     检定技能值为99的毁灭人类技能",
示例可以等后面再写，我到时候会加一个example的项

2024-04-09 13:51 UTC, fu050409 approved these changes

2024-04-09 13:53 UTC, fu050409 requested changes
前面`sub_cmd`你没有做出更改

2024-04-10 06:24 UTC, BegoniaHe commented on src/handlers.py
> +    description="基础属性或技能检定\n示例：\n.ra 命运    快速检定`命运`属性\n.ra 毁灭人类 99     检定技能值为99的毁灭人类技能",
🆗

2024-04-14 15:55 UTC, fu050409 approved these changes

2024-04-14 15:55 UTC, merged